### ISSUE TITLE
Get cookbook-repose on Supermarket

### ISSUE THREAD

**Issue by filler** [rackerlabs/cookbook-repose#56]
# Description

Begin publishing this cookbook to supermarket.chef.io.
# Todo / Tasks
- [x] add stove to the repository
- [x] add to the supermarket
- [x] add current collaborators to have access to publish updated versions 
# How to test

Add to Berksfile and pull from the supermarket.  
# Acceptance Criteria

Cookbook is published to the supermarket and at least 3 collaborators (at least two different internal Rackspace teams) have access to update it and add other collaborators.
# original issue

Someone needs to do the needful.

It also needs to be done in a way which allows ownership to survive Racker attrition.  eg dont set this up under a personal chef.io account which walks with a Racker who separates.

**Comment by filler** [comment]
If need be, we should pop an externally-deliverable distribution list in Exchange to allow maintainers to have insight into comms from users and/or chef.io supermarket comms.

**Comment by filler** [comment]
Pinged the Service Desk at `INC0277202` to see about setting up said dlist at `cookbook-repose@` ...

**Comment by drenalin23** [comment]
References -
https://github.com/sethvargo/stove
https://www.chef.io/blog/2015/03/16/using-chef-supermarket-a-guided-tour/

**Comment by filler** [comment]
`cookbook-repose@` is now an externally deliverable dlist in Exchange, so we are good to use that for Supermarket signups and `metadata.rb` as appropriate.

**Comment by filler** [comment]
Ive never used stove.  Last I looked at it, it seemed pretty opinionated.  That said I have little XP maintaining a book in the market so whatever is best of breed is ok by me.  💯
